light.kitchen_level:
  refresh_value: true
  delay: 2
  polling_intensity: 0
  ignored: false
light.dining_room_level:
  refresh_value: true
  delay: 2
  polling_intensity: 0
  ignored: false
zwave.kwikset_touchpad_electronic_deadbolt_9:
  ignored: false
  polling_intensity: 1
light.front_porch_level:
  ignored: false
  polling_intensity: 0
light.living_room_level:
  ignored: false
  polling_intensity: 0
light.garage_level:
  ignored: false
  polling_intensity: 0
light.master_bedroom_level:
  ignored: false
  polling_intensity: 0
switch.hallway_closet_switch:
  ignored: false
  polling_intensity: 1
light.upstairs_light_1_level:
  ignored: false
  polling_intensity: 1
light.upstairs_light_2_level:
  ignored: false
  polling_intensity: 1
zwave.upstairs_light_2:
  ignored: false
  polling_intensity: 1
zwave.upstairs_light_1:
  ignored: false
  polling_intensity: 1
